[build]
  command = "npm run build"
  publish = "build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[functions]
  directory = "netlify/functions"