name: Docker Image CI for GHCR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_publish:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u cyberrain94 --password-stdin

    - name: Build and push the Docker image
      run: |
        docker build -f Dockerfile -t ghcr.io/cyberrain94/personal-link-tree:latest .
        docker push ghcr.io/cyberrain94/personal-link-tree:latest
